# SERVER PROFILES
server:
  port: 11007

# SPRING PROFILES
spring:
 profiles:
    active: 130

 redis.database: 0
 redis.host: 127.0.0.1
 redis.password: 123456
 redis.pool.max-active: 8
 redis.pool.max-wait: -1
 redis.pool.max-idle: 8
 redis.pool.min-idle: 0
 redis.timeout: 0
 redis.port: 6379

 rabbitmq:
  host: 192.168.10.212
  port: 5672
  username: guest
  password: guest
  virtualHost: /

