logging:
  level:
    root: ERROR
  config: classpath:logback-spring.xml
# SPRING PROFILES
spring:
  #DATASOURCE
  datasource:
    url: jdbc:log4jdbc:mysql://192.168.1.202:3306/wms_v8_staging?useUnicode=true&characterEncoding=utf8&useSSL=false
    #url: jdbc:log4jdbc:mysql://192.168.1.202:3306/wms_v8_staging?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: net.sf.log4jdbc.DriverSpy
    hikari:
      idleTimeout: 70
      maximumPoolSize: 15

  # JPA
  jpa:
    database: MYSQL
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLInnoDBDialect
    generate-ddl: false
    hibernate:
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none

  rabbitmq:
    host: 192.168.1.202
    port: 5672
    username: guest
    password: guest
    virtualhost: /
  # JACKSON
  jackson:
    serialization.write-dates-as-timestamps: false
    serialization.indent_output: true
security:
  oauth2:
    client:
      client-id: wms-internaltool-service-v8
      client-secret: wms-internaltool-service-v8
      access-token-uri: http://192.168.1.202:9998/uaa/oauth/token
      user-authorization-uri:
      clientAuthenticationScheme: form
      grant-type: client_credentials
      scope: server
    resource:
      token-info-uri: http://192.168.1.202:9998/uaa/oauth/check_token
      prefer-token-info: false