# SERVER PROFILES
server:
  port: 11010

logging:
  level:
    jdbc.sqltming: INFO  #记录sql执行语句及时间
    jdbc.sqlonly: OFF
    jdbc.audit: OFF
    jdbc.resultset: OFF
    jdbc.resultsettable: OFF
    jdbc.connection: OFF

# SPRING PROFILES
spring:
 profiles:
    active: 249


